### ISSUE TITLE
v2.8

### ISSUE THREAD

**Issue by evil-morfar** [evil-morfar/RCLootCouncil2#150]
**Mandatory**
- [x] - Personal Loot
- - [x] - Changes to "Auto Loot BoE" 
- [x] - Trade Windows

**Included if ready**

- [ ] - Autopass owned items #153
- [x] - Discord export
- [ ] - Optimize reconnect data #125
- [x] - /rc add run by everyone #88
- [ ] - Loot Frame shows compare item #142
- [ ] - Better export filters

**Nice to have, but might be pushed**
- Export SV in game #134 
-  #143
- #147 
- Mass deletion of Loot History
- #155 
- #156

**Comment by SafeteeWoW** [comment]
Just hope Argus is dead this week, so I may help a bit. #134 is close to finish, and it is just untouched for a while. Adding some filters to #143 is not hard, and it is a nice feature to have.

#125 is a bit complicated, and I am not sure if it should be in v2.8. It could be a part of v3

**Comment by evil-morfar** [comment]
I've already started on #125 - I'm only missing the receiving part of it. The reason I want to do it now is a `reconnect` command has the potential to fill the comms buffer thus delaying everything significantly. The only remaining question is which serializer to use, and if LibCompress should be used as well.

**Comment by SafeteeWoW** [comment]
Dont change the serialize or use LibCompress which breaks all compatibility.
The new serializer isn't ready yet.
Full compatibility break should come in the next expansion, or in the pre-patch.

**Comment by SafeteeWoW** [comment]
I dont think all these changes should be in v2.8. Many should be in v3.0, because I don't think RCLootCouncil is very important addon at the end of expansion. Since we're going to restructure RCLootCouncil in v3.0 anyway, it's better to implement some features there instead.

**Comment by SafeteeWoW** [comment]
I dont think all these changes should be in v2.8. Many should be in v3.0, because I don't think RCLootCouncil is very important addon at the end of expansion. Since we're going to restructure RCLootCouncil in v3.0 anyway, it's better to implement some features there instead.

**Comment by SafeteeWoW** [comment]
I have planned to implement pure LUA version of DEFLATE algorithm, which is used by zip. According to my tests, it takes ~200 bytes to transmit all equipped item strings if the data is compressed by zip. However, it will be long time if I manage to make it work and fast. Speed expectation: as fast as libcompress's ```CompressLZW+CompressHuffman```

**Comment by evil-morfar** [comment]
>> I dont think all these changes should be in v2.8.

That's why I've mostly chosen those that's almost finished anyway. I'd very much like to get the PL stuff out now while especially many uses PL, to get a feel for how it's received. The rest is just optimizations, a lot of which is easily reuseable in later versions.

>>I don't think RCLootCouncil is very important addon at the end of expansion

While true, it's not the right mindset to have, and is no excuse for not doing any updates (a lot of people still use it). Besides, I'd rather do new features and get feedback now where any potential shortcomings doesn't matter too much, than finding out at the start of the next xpac that feature x breaks everything.

>>LUA version of DEFLATE algorithm

If you think it's worth it, then cool.

**Comment by evil-morfar** [comment]
2.8 is released, not all of the bullets made it into the release though. Closing this.
